# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.1.0
  docker: circleci/docker@1.7.0
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install:
          install-yarn: true 
          node-version: '18' 
          yarn-version: '1.22.19' 

workflows:
  example-workflow:
    jobs:
      - example-job