version: 2.1
orbs:
  node: circleci/node@5.1.0
  docker: circleci/docker@1.7.0
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  builTest:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "16.13"
      # - run: node --version
      # - run:
      #     name: yarn install
      #     command: yarn install
      # - run:
      #     name: yarn build
      #     command: yarn run build
  buildContianer:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: check command
          command: echo $CIRCLE_SHA1 
      # - setup_remote_docker
      # - digitalocean/install
      # - digitalocean/initialize:
      #     digitalocean-access-token: DIGITALOCEAN_ACCESS_TOKEN
      # - docker/build:
      #     attach-at: .
      #     debug: true
      #     docker-context: .
      #     image: yogi-nextjs
      #     lint-dockerfile: false
      #     path: ./
      #     treat-warnings-as-errors: false
      # - doctl/install_and_initialize_cli:
      #     context: credential
      #     executor: doctl/default
      # - run:
      #     name: tagdocker docker image
      #     command: docker tag yogi-nextjs registry.digitalocean.com/yogimaps-container-registry/yogi-nextjs
      # - run:
      #     name: push docker image
      #     command: docker push registry.digitalocean.com/yogimaps-container-registry/yogi-nextjs
workflows:
  # example-workflow:
  #   jobs:
  #     - builTest
  docker-build-workflow:
    jobs:
      # - builTest
      - buildContianer:
          filters:
            branches:
              only: autodeployment